Catalogo de servicos e funcionarios
AleeLouffer/ProjetoIntegrador pull request #1
Opened 2021-09-13 20:56 UTC by AleeLouffer

2021-09-16 22:03 UTC, vsaueia requested changes
Avaliem os comentários se fazem sentido e estou a disposição em caso de dúvida

2021-09-16 22:03 UTC, vsaueia commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Repositorio/Repositorio_Funcionario.cs
> +                funcionarios.Add(_contexto.Set<Funcionario>().Where(f => f.Id == id).SingleOrDefault());
apesar de relativamente comum eu não gosto desse tipo de nome para variável interna "f", pode usar o nome significativo e o "clean code" agradece "funcionario.Id == id"

2021-09-16 22:03 UTC, vsaueia commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Repositorio/Repositorio_FuncionariosComServicos.cs
> +            for (int i = 0; i < qtdFuncionarios; i++)
qtd, abreviação

2021-09-29 14:18 UTC, viniciuslima-dgx requested changes

2021-09-29 14:18 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/PI.Testes/RepositorioFuncionariosComServicosTeste.cs
> +            var idFuncionario = _repositorio.BuscarIdsDosFuncionariosPeloIdDoServico(idEsperado);
Fora do padrão AAA.

2021-09-29 14:18 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Repositorio/RepositorioFuncionario.cs
> +        public bool VerificarFuncionarioExistente(Funcionario funcionario)
Esse método é custoso. Por que não seguir a ideia de busca usada no BuscarFuncionariosPorIds?

2021-09-29 19:01 UTC, viniciuslima-dgx requested changes

2021-09-29 19:01 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Repositorio/RepositorioServico.cs
> +            var servicosDoBanco = _contexto.Set<Servico>().ToList();
Essa linha 37 vai trazer todos serviços existentes no banco pra memória. Sugiro mudar a abordagem para tipo a do repositório de funcionário, ou algo genérico como conversei com o Daniel

2021-09-29 19:12 UTC, viniciuslima-dgx approved these changes

2021-09-29 19:13 UTC, merged