Adicionando Teste De Objeto Anônimo No Agendamento
AleeLouffer/ProjetoIntegrador pull request #12
Opened 2021-10-27 19:54 UTC by DanielZanelato

2021-11-08 21:00 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Models/Operacoes/Agendamento.cs
> +        public static DateTime ObterComoHoraEData(string dataEHora)
Por qual motivo isso foi para public? 
Me parece algo de uso interno, ou deveria estar fora daqui como uma extensão de string ou algo assim.

2021-11-08 21:05 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/PI.Testes/AgendamentoTeste.cs
> +            var agendamento = new Agendamento(_funcionario, _empresa, _servico, _horaEData, _cliente);
Por qual motivo o agendamento já não recebe um DateTime ao invés de uma string de data e hora? Não me parece responsabilidade do negócio saber converter corretamente um padrão de data em hora em texto para datetime, até porque esse padrão em texto pode variar dependendo de onde esse dado vem.

2021-11-10 17:50 UTC, viniciuslima-dgx approved these changes

2021-11-10 17:51 UTC, viniciuslima-dgx requested changes

2021-11-10 17:51 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Models/Operacoes/Agendamento.cs
> -            if (string.IsNullOrWhiteSpace(horario)) throw new Exception("O campo horário deve ser preenchido");
Faz sentido um agendamento no passado?

2021-11-17 17:49 UTC, vsaueia approved these changes

2021-11-17 17:49 UTC, merged