Adicionando empresa
AleeLouffer/ProjetoIntegrador pull request #8
Opened 2021-10-06 20:18 UTC by AleeLouffer-zz

2021-10-18 14:36 UTC, vsaueia commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Models/EnderecoDaEmpresa.cs
> +        public int Id { get; set; }
O endereço da empresa não precisa ser uma entidade a parte, ela pode ser uma composição (vale a pena olhar para embedded ou objeto de valor por exemplo)

2021-10-18 14:37 UTC, vsaueia commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Models/Operacoes/Servico.cs
> +        public int EmpresaId { get; private set; }
Porque não ter a Empresa aqui ao invés do identificador apenas?

2021-10-19 21:07 UTC, viniciuslima-dgx requested changes

2021-10-19 21:07 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Models/Mapeamentos/EmpresaMap.cs
> +//    {
E esse arquivo comentado?

2021-10-19 21:07 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Models/ObjetoDeValor.cs
> +    public abstract class ObjetoDeValor
Qual a necessidade dessa classe no momento? Lembrem do yagni

2021-10-20 17:26 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Models/EnderecoDaEmpresa.cs
> +            var endereco = new ViaCEP().GetEndereco(cep);
E se isso aqui falhar? Não encontrar o endereço para o cep informado?

2021-10-20 21:02 UTC, merged