Implementando excessao no banco
AleeLouffer/ProjetoIntegrador pull request #9
Opened 2021-10-13 20:44 UTC by DanielZanelato

2021-10-18 14:42 UTC, vsaueia commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Repositorio/BaseRepositorio.cs
> +            catch (DbUpdateException ex)
Como está sendo capturado a exceção na camada de infra, o ponto que chamou o método precisa estar preparado para não ter a resposta como gostaria

2021-10-18 14:42 UTC, vsaueia commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Repositorio/BaseRepositorio.cs
> +            catch (DbUpdateException ex)
O ideal é sempre subir a exceção para quem está acima na cadeia a menos que tenha algo que posso ser feito no tratamento da exceção

2021-10-19 18:49 UTC, viniciuslima-dgx requested changes

2021-10-19 18:49 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Repositorio/BaseRepositorio.cs
> +        private static bool ExisteNoBanco(SqlException innerException)
Dois problemas com esse método. O primeiro é que o nome dele não é verbo. Outro ponto é que o nome da a entender que estamos validando se a exceção existe no banco e não se a exceção é de duplicação de dados.
Sugiro deixar isso como um bool no próprio catch, algo como` excecaoRepresentaDuplicidade = innerException.Number == 2627 || innerException.Number == 2601;`

2021-10-19 18:49 UTC, viniciuslima-dgx commented on ProjetoIntegradorMVC/ProjetoIntegradorMVC/Repositorio/BaseRepositorio.cs
> +                throw;
Os locais no código que chamam esse método estão tratando essa possível exceção? Ou existe algum middleware no projeto que trate elas?

2021-10-20 20:48 UTC, merged